(件名なし)
crystal-parleaf@docomo.ne.jp
​
自分
​
[ // 省略: 大アルカナ22枚 + 小アルカナ カップ & ソード28枚

// 小アルカナ ワンド { "name": "ワンドのエース", "image": "https://upload.wikimedia.org/wikipedia/commons/1/11/Wands01.jpg", "upright": "創造性、始まり、情熱", "reversed": "遅れ、可能性の喪失" }, { "name": "ワンドの2", "image": "https://upload.wikimedia.org/wikipedia/commons/0/0f/Wands02.jpg", "upright": "計画、未来展望、選択", "reversed": "不安、決断の欠如" }, { "name": "ワンドの3", "image": "https://upload.wikimedia.org/wikipedia/commons/f/ff/Wands03.jpg", "upright": "拡大、進展、ビジョン", "reversed": "停滞、失望" }, { "name": "ワンドの4", "image": "https://upload.wikimedia.org/wikipedia/commons/0/04/Wands04.jpg", "upright": "安定、祝福、家庭", "reversed": "緊張、分裂" }, { "name": "ワンドの5", "image": "https://upload.wikimedia.org/wikipedia/commons/9/9b/Wands05.jpg", "upright": "競争、対立、挑戦", "reversed": "混乱、回避" }, { "name": "ワンドの6", "image": "https://upload.wikimedia.org/wikipedia/commons/7/7b/Wands06.jpg", "upright": "勝利、評価、達成", "reversed": "過信、挫折" }, { "name": "ワンドの7", "image": "https://upload.wikimedia.org/wikipedia/commons/e/e4/Wands07.jpg", "upright": "防御、主張、挑戦への立ち向かい", "reversed": "防御の失敗、弱さ" }, { "name": "ワンドの8", "image": "https://upload.wikimedia.org/wikipedia/commons/6/6b/Wands08.jpg", "upright": "急展開、行動、勢い", "reversed": "遅延、混乱" }, { "name": "ワンドの9", "image": "https://upload.wikimedia.org/wikipedia/commons/4/4d/Wands09.jpg", "upright": "忍耐、防御、疲労", "reversed": "諦め、不安" }, { "name": "ワンドの10", "image": "https://upload.wikimedia.org/wikipedia/commons/0/0b/Wands10.jpg", "upright": "重荷、責任、努力", "reversed": "解放、圧倒" }, { "name": "ワンドのペイジ", "image": "https://upload.wikimedia.org/wikipedia/commons/1/11/Wands11.jpg", "upright": "冒険、ひらめき、情熱の始まり", "reversed": "落ち着きのなさ、未熟" }, { "name": "ワンドのナイト", "image": "https://upload.wikimedia.org/wikipedia/commons/6/6a/Wands12.jpg", "upright": "冒険心、行動力、熱意", "reversed": "衝動、無謀" }, { "name": "ワンドのクイーン", "image": "https://upload.wikimedia.org/wikipedia/commons/1/1c/Wands13.jpg", "upright": "魅力、自信、独立", "reversed": "嫉妬、自己中心" }, { "name": "ワンドのキング", "image": "https://upload.wikimedia.org/wikipedia/commons/2/2b/Wands14.jpg", "upright": "リーダーシップ、情熱、行動力", "reversed": "支配欲、衝動" },

// 小アルカナ ペンタクル { "name": "ペンタクルのエース", "image": "https://upload.wikimedia.org/wikipedia/commons/9/96/Pents01.jpg", "upright": "繁栄、機会、物質的成功", "reversed": "機会の喪失、貪欲" }, { "name": "ペンタクルの2", "image": "https://upload.wikimedia.org/wikipedia/commons/f/fd/Pents02.jpg", "upright": "バランス、柔軟性、調整", "reversed": "優柔不断、不安定" }, { "name": "ペンタクルの3", "image": "https://upload.wikimedia.org/wikipedia/commons/2/2b/Pents03.jpg", "upright": "協力、技術、進歩", "reversed": "協調性の欠如、未熟" }, { "name": "ペンタクルの4", "image": "https://upload.wikimedia.org/wikipedia/commons/9/99/Pents04.jpg", "upright": "保守、所有欲、安定", "reversed": "手放す、強欲" }, { "name": "ペンタクルの5", "image": "https://upload.wikimedia.org/wikipedia/commons/9/96/Pents05.jpg", "upright": "困難、損失、孤独", "reversed": "回復、希望" }, { "name": "ペンタクルの6", "image": "https://upload.wikimedia.org/wikipedia/commons/8/86/Pents06.jpg", "upright": "援助、分配、寛大さ", "reversed": "不公平、依存" }, { "name": "ペンタクルの7", "image": "https://upload.wikimedia.org/wikipedia/commons/7/70/Pents07.jpg", "upright": "評価、忍耐、長期的視点", "reversed": "焦り、失望" }, { "name": "ペンタクルの8", "image": "https://upload.wikimedia.org/wikipedia/commons/8/88/Pents08.jpg", "upright": "努力、技能の向上、集中", "reversed": "怠惰、無関心" }, { "name": "ペンタクルの9", "image": "https://upload.wikimedia.org/wikipedia/commons/d/d1/Pents09.jpg", "upright": "独立、裕福、自立", "reversed": "不安定、損失" }, { "name": "ペンタクルの10", "image": "https://upload.wikimedia.org/wikipedia/commons/4/42/Pents10.jpg", "upright": "財産、家族、伝統", "reversed": "財政トラブル、崩壊" }, { "name": "ペンタクルのペイジ", "image": "https://upload.wikimedia.org/wikipedia/commons/d/d4/Pents11.jpg", "upright": "新しい計画、学習、信頼性", "reversed": "遅延、不注意" }, { "name": "ペンタクルのナイト", "image": "https://upload.wikimedia.org/wikipedia/commons/e/ec/Pents12.jpg", "upright": "安定、勤勉、信頼性", "reversed": "頑固、停滞" }, { "name": "ペンタクルのクイーン", "image": "https://upload.wikimedia.org/wikipedia/commons/7/78/Pents13.jpg", "upright": "現実的、実り、世話好き", "reversed": "物質主義、過干渉" }, { "name": "ペンタクルのキング", "image": "https://upload.wikimedia.org/wikipedia/commons/f/fd/Pents14.jpg", "upright": "成功、豊かさ、安定", "reversed": "贅沢、頑固" } ]
